export enum FormulaName {
  /**
   * Math.
   */
  ABS = "ABS",
  ACOS = "ACOS",
  ACOSH = "ACOSH",
  ACOT = "ACOT",
  ACOTH = "ACOTH",
  ADD = "ADD",
  ASIN = "ASIN",
  ASINH = "ASINH",
  ATAN = "ATAN",
  ATAN2 = "ATAN2",
  ATANH = "ATANH",
  COS = "COS",
  COSH = "COSH",
  COT = "COT",
  DIVIDE = "DIVIDE",
  EVEN = "EVEN",
  INT = "INT",
  ISEVEN = "ISEVEN",
  ISODD = "ISODD",
  LN = "LN",
  LOG = "LOG",
  LOG10 = "LOG10",
  MINUS = "MINUS",
  MOD = "MOD",
  MULTIPLY = "MULTIPLY",
  ODD = "ODD",
  PI = "PI",
  POW = "POW",
  POWER = "POWER",
  PRODUCT = "PRODUCT",
  QUOTIENT = "QUOTIENT",
  RAND = "RAND",
  RANDBETWEEN = "RANDBETWEEN",
  ROUND = "ROUND",
  FLOOR = "FLOOR",
  ROUNDDOWN = "ROUNDDOWN",
  ROUNDUP = "ROUNDUP",
  SIGN = "SIGN",
  SIN = "SIN",
  SINH = "SINH",
  SQRT = "SQRT",
  SQRTPI = "SQRTPI",
  SUM = "SUM",
  TAN = "TAN",
  TANH = "TANH",
  UMINUS = "UMINUS",
  UPLUS = "UPLUS",
  UNARY_PERCENT = "UNARY_PERCENT",
  /**
   * Statistical.
   */
  AVEDEV = "AVEDEV",
  AVERAGE = "AVERAGE",
  AVERAGEA = "AVERAGEA",
  AVERAGEIF = "AVERAGEIF",
  COUNT = "COUNT",
  COUNTA = "COUNTA",
  COUNTBLANK = "COUNTBLANK",
  MAX = "MAX",
  MAXA = "MAXA",
  MIN = "MIN",
  MINA = "MINA",
  STDEV = "STDEV",
  /**
   * Info.
   */
  ERRORTYPE = "ERRORTYPE",
  ISBLANK = "ISBLANK",
  ISERR = "ISERR",
  ISERROR = "ISERROR",
  ISLOGICAL = "ISLOGICAL",
  ISNA = "ISNA",
  ISNONTEXT = "ISNONTEXT",
  ISNUMBER = "ISNUMBER",
  ISTEXT = "ISTEXT",
  N = "N",
  NA = "NA",
  TYPE = "TYPE",
  /**
   * Text.
   */
  CONCAT = "CONCAT",
  CONCATENATE = "CONCATENATE",
  LEN = "LEN",
  T = "T",
  /**
   * Engineering.
   */
  BIN2DEC = "BIN2DEC",
  BIN2HEX = "BIN2HEX",
  DELTA = "DELTA",
  /**
   * Parser.
   */
  TO_PERCENT = "TO_PERCENT",
  TO_TEXT = "TO_TEXT",
  /**
   * Lookup.
   */
  CHOOSE = "CHOOSE",
  /**
   * Logical
   */
  AND = "AND",
  EQ = "EQ",
  EXACT = "EXACT",
  FALSE = "FALSE",
  GT = "GT",
  GTE = "GTE",
  IF = "IF",
  IFERROR = "IFERROR",
  IFNA = "IFNA",
  LT = "LT",
  LTE = "LTE",
  NE = "NE",
  NOT = "NOT",
  OR = "OR",
  TRUE = "TRUE",
  XOR = "XOR",
  /**
   * Unknown. For testing only.
   */
  UNKNOWN = "UNKNOWN",
}

export const AllFormulaNames = new Set([
  FormulaName.ABS,
  FormulaName.ACOS,
  FormulaName.ACOSH,
  FormulaName.ACOT,
  FormulaName.ACOTH,
  FormulaName.ADD,
  FormulaName.ASIN,
  FormulaName.ASINH,
  FormulaName.ATAN,
  FormulaName.ATAN2,
  FormulaName.ATANH,
  FormulaName.COS,
  FormulaName.COSH,
  FormulaName.COT,
  FormulaName.DIVIDE,
  FormulaName.EVEN,
  FormulaName.INT,
  FormulaName.ISEVEN,
  FormulaName.ISODD,
  FormulaName.LN,
  FormulaName.LOG,
  FormulaName.LOG10,
  FormulaName.MINUS,
  FormulaName.MOD,
  FormulaName.MULTIPLY,
  FormulaName.ODD,
  FormulaName.PI,
  FormulaName.POW,
  FormulaName.POWER,
  FormulaName.PRODUCT,
  FormulaName.QUOTIENT,
  FormulaName.RAND,
  FormulaName.RANDBETWEEN,
  FormulaName.ROUND,
  FormulaName.ROUNDDOWN,
  FormulaName.ROUNDUP,
  FormulaName.SIGN,
  FormulaName.SIN,
  FormulaName.SINH,
  FormulaName.SQRT,
  FormulaName.SQRTPI,
  FormulaName.SUM,
  FormulaName.TAN,
  FormulaName.TANH,
  FormulaName.UMINUS,
  FormulaName.UPLUS,
  FormulaName.UNARY_PERCENT,
  FormulaName.AVEDEV,
  FormulaName.AVERAGE,
  FormulaName.AVERAGEA,
  FormulaName.COUNT,
  FormulaName.COUNTA,
  FormulaName.COUNTBLANK,
  FormulaName.MAX,
  FormulaName.MAXA,
  FormulaName.MIN,
  FormulaName.MINA,
  FormulaName.STDEV,
  FormulaName.ERRORTYPE,
  FormulaName.ISBLANK,
  FormulaName.ISERR,
  FormulaName.ISERROR,
  FormulaName.ISLOGICAL,
  FormulaName.ISNA,
  FormulaName.ISNONTEXT,
  FormulaName.ISNUMBER,
  FormulaName.ISTEXT,
  FormulaName.N,
  FormulaName.NA,
  FormulaName.TYPE,
  FormulaName.CONCAT,
  FormulaName.CONCATENATE,
  FormulaName.LEN,
  FormulaName.T,
  FormulaName.TO_PERCENT,
  FormulaName.TO_TEXT,
  FormulaName.CHOOSE,
  FormulaName.AND,
  FormulaName.EQ,
  FormulaName.EXACT,
  FormulaName.FALSE,
  FormulaName.GT,
  FormulaName.GTE,
  FormulaName.IF,
  FormulaName.IFERROR,
  FormulaName.IFNA,
  FormulaName.LT,
  FormulaName.LTE,
  FormulaName.NE,
  FormulaName.NOT,
  FormulaName.OR,
  FormulaName.TRUE,
  FormulaName.XOR,
  FormulaName.BIN2DEC,
  FormulaName.BIN2HEX,
  FormulaName.XOR,
  FormulaName.UNKNOWN,
  FormulaName.FLOOR,
  FormulaName.DELTA,
]);
